spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carteira?autoReconnect=true&useSSL=false
    username: carteira-user
    password: gordimSafado

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    open-in-view: false

logging:
  level:
    root: info
    org.springframework.security: DEBUG